/* DO NOT EDIT THIS FILE - it is machine generated */


#include <jni.h>
/* Header for class com_nostra13_universalimageloader_gif_GifFactory */

#ifndef _Included_com_baidu_iknow_gif_GifFactory
#define _Included_com_baidu_iknow_gif_GifFactory
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL lockBitmap(JNIEnv *, jclass,jobject);

JNIEXPORT void JNICALL unlockBitmap(JNIEnv *, jclass,jobject);

#ifdef __cplusplus
}
#endif
#endif
