/* DO NOT EDIT THIS FILE - it is machine generated */


#include <jni.h>
/* Header for class com_nostra13_universalimageloader_gif_GifFactory */

#ifndef _Included_com_baidu_iknow_gif_GifFactory
#define _Included_com_baidu_iknow_gif_GifFactory
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL writeFrameToBitmap(JNIEnv *, jobject, jint, jobject);

JNIEXPORT void JNICALL nativeRelease(JNIEnv *, jobject);

JNIEXPORT jobject JNICALL decodeFromFile(JNIEnv *, jclass, jstring, jobject);

JNIEXPORT jobject JNICALL decodeFromByteArray(JNIEnv *, jclass, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
